---
title: "Manu Davo"
---


Bienvenido a la web del libro [__Análisis Forense en Sistemas Windows__](www.amazon.es)

Este libro pretende ser un manual de referencia destinado a policías, investigadores, administradores de sistemas, estudiantes y profesionales de la seguridad TI. Pero no te preocupes si no estás en ninguno de estos colectivos, este libro va destinado, sobre todo, para gente curiosa y con ganas de aprender.
El análisis forense permite recabar información de las acciones que se han llevado a cabo un sistema operativo, obteniendo pruebas que permitan esclarecer un incidente de seguridad o una acción delictiva para la cual se ha utilizado el sistema operativo en cuestión. 
Estudiaremos diferentes métodos de recopilación de datos de un sistema Windows, el sistema operativo más usado en ordenadores portátiles y equipos de escritorio. Te mostraré una parte teórica que nos descubra el funcionamiento interno del sistema operativo, y trabajaremos con muchos ejemplos prácticos que nos ayudarán a consolidar la teoría. 

 
Con este libro aprenderás:
- Qué rastros quedan en el sistema al ejecutar un programa, o abrir un simple archivo.
- Cómo recuperar archivos que han sido borrados de manera accidental, o no tan accidental.
- Cómo se pueden ocultar gigabytes de información en un archivo y que éste último no aumente de tamaño ni un solo byte, mediante los flujos de datos alternativos.
- Cómo los modos de navegación incógnito de los diferentes navegadores, en realidad no son tan incógnitos.
- Cómo analizar un correo electrónico para poder determinar su autenticidad.
- Cómo realizar una línea de tiempo donde queden reflejadas todas las acciones que han ocurrido en un intervalo temporal.
- Cómo montar máquinas virtuales con las que realizar las prácticas.
- También daremos un repaso a algunas técnicas antiforense, usadas para ocultar las acciones realizadas.
- Y bastantes cosas más.

Lo puedes adquirir en Amazon haciendo click [__AQUÍ__](www.amazon.es)

En la pestaña descargas podrás descargarte de manera gratuita el software de triage forense [__Davo__](..\descargas)